# Aliases
alias gc='git checkout'
alias gb='git branch'
alias gba='git branch -a'
alias gco='git commit -v'
alias gd='git diff'
alias gl='git pull'
alias gp='git push'
alias gst='git status'
alias gadd='git add'
alias grb='git rebase'
